export const WIPE_STATE = 'WIPE_STATE';

export const GET_GIFS_REQUEST = 'GET_GIFS_REQUEST';
export const GET_GIFS_SUCCESS = 'GET_GIFS_SUCCESS';
export const GET_GIFS_FAILED = 'GET_GIFS_FAILED';

export const GET_TREND_REQUEST = 'GET_TREND_REQUEST';
export const GET_TREND_SUCCESS = 'GET_TREND_SUCCESS';
export const GET_TREND_FAILED = 'GET_TREND_FAILED';

export const GET_RATED_REQUEST = 'GET_RATED_REQUEST';
export const GET_RATED_SUCCESS = 'GET_RATED_SUCCESS';
export const GET_RATED_FAILED = 'GET_RATED_FAILED';

export const GET_RATINGS_REQUEST = 'GET_RATINGS_REQUEST';
export const GET_RATINGS_SUCCESS = 'GET_RATINGS_SUCCESS';
export const GET_RATINGS_FAILED = 'GET_RATINGS_FAILED';

export const SET_RATING = 'SET_RATING';
export const SET_RATING_REQUEST = 'SET_RATING_REQUEST';
export const SET_RATING_SUCCESS = 'SET_RATING_SUCCESS';
export const SET_RATING_FAILED = 'SET_RATING_FAILED';

export const SET_ACTIVE_ITEM = 'SET_ACTIVE_ITEM';
export const NEW_SEARCH = 'NEW_SEARCH';
export const END_OF_GIFS = 'END_OF_GIFS';
export const LOAD = 'LOAD';
export const SET_MODE = 'SET_MODE';

export const LOAD_RATINGS = 'LOAD_RATINGS';
export const SAVE_RATINGS = 'SAVE_RATINGS';

